version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    image: web
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
